### PR TITLE
IMDB Example

### PR DESCRIPTION
**Pull request by AlexWan0**
1) Includes a notebook example for sentiment analysis on the IMDB dataset

2)
IPython notebooks don't have a \_\_file__ attribute, causing it to throw an error when attempting to get programName.

Particularly, here's the code the replicate it: https://colab.research.google.com/drive/11sqYyV7lJz6hNZ4yYuLp2p33wvzkueDT?usp=sharing
It throws an AttributeError when initializing SolverPOIProgram.

There doesn't seem to be a good way to get the filename of a IPython notebook, however.

### CODE REVIEW

**Comment by kordjamshidi** [comment]
@hfaghihi15 please see if this code is ok to merge as a new Sentiment analysis example with a different dataset compared to our current example. 
@AlexWan0 do you have a reference to the source of the data and boost recent results on that? are your resumes comparable?

**Comment by hfaghihi15** [comment]
@kordjamshidi This seems more like a standalone version of a demo for IMDB but not an example in the system.
We may have to change the format also from the python to python files and fix the paths.

**Comment by kordjamshidi** [comment]
@hfaghihi15 are you sure, I can not open the python notebook here but I think it was based on forming the graph and defining learners and binary constraints last time that I checked. @AlexWan0

**Comment by AlexWan0** [comment]
I wrote it pretty similar to the notebook examples in the tutorials folder. It wouldn't be too hard for me to change it to the format in  /examples.

**Comment by AlexWan0** [comment]
The source of the data is: https://ai.stanford.edu/~amaas/data/sentiment/ and recent results can be found here: https://paperswithcode.com/sota/sentiment-analysis-on-imdb

I'd say the accuracy here is generally on-par with other results given the simplicity of the model (i.e. just an LSTM + embeddings).

**Comment by hfaghihi15** [comment]
> @hfaghihi15 are you sure, I can not open the python notebook here but I think it was based on forming the graph and defining learners and binary constraints last time that I checked. @AlexWan0

The first block of the code tries to git clone the repo and so on. That's why I said this is more a standalone tutorial for the framework and different from the examples. 

It would be good to keep both example version and tutorial version anyway but place them under their appropriate folders.

**Pull request merged**
