### PR TITLE
Develop new lc

### PR DESCRIPTION
**Pull request by hfaghihi15**
Merge the new changes and updates to make a stable develop branch

### CODE REVIEW

**Review by kordjamshidi — APPROVED** [review]
This is ok to me to merge.

**Review by auszok — DISMISSED** [review]
Agree

**Comment by kordjamshidi** [comment]
it seems the Semaphore is not disabled, right?

**Comment by kordjamshidi** [comment]
Closing this to reopen.

**Review by kordjamshidi — APPROVED** [review]

**Pull request closed without merging**
